# -*- coding: utf-8 -*-
"""streamlit_gasto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15zbxfGPHYewLK37RU2uK6slJHmolukeq
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# === Título ===
st.write(''' # Predicción de Costo de Actividades Diarias ''')
st.markdown("Ingresa los datos de tu próxima actividad para estimar cuánto gastarás.")
# st.image("logo.png", use_column_width=True) # Commented out as logo.png was not found

# === Cargar y preparar los datos ===
# Aquí debes tener tu archivo 'registrodatos.csv' en la misma carpeta que este script
try:
    df = pd.read_csv('registrodatos.csv', encoding='latin1')
except FileNotFoundError:
    st.error("⚠️ No se encontró el archivo 'registrodatos.csv'. Asegúrate de incluirlo.")
    st.stop()

# Eliminar columnas innecesarias
df.drop(['Número', 'Fecha (dd/mm/aa)', 'Nombre actividad'], axis=1, inplace=True, errors='ignore')

# Corregir errores comunes
df['Tipo'] = df['Tipo'].str.strip()
df['Momento'] = df['Momento'].str.strip()
correcciones = {
    'Alimenos': 'Alimentos',
    'Aliemntos': 'Alimentos',
    'Trasporte': 'Transporte',
    'gaoslina': 'Transporte',
    'gaolina': 'Transporte'
}
df['Tipo'] = df['Tipo'].replace(correcciones)

# Mapeo según la descripción oficial
tipo_map = {'Alimentos': 1, 'Salud': 1, 'Transporte': 6, 'Entretenimiento': 4}
momento_map = {'Manana': 1, 'Tarde': 2, 'Noche': 3}

df['Tipo_cod'] = df['Tipo'].map(tipo_map)
df['Momento_cod'] = df['Momento'].map(momento_map)

# Eliminar filas con mapeo inválido
df = df.dropna(subset=['Tipo_cod', 'Momento_cod'])
df['Tipo_cod'] = df['Tipo_cod'].astype(int)
df['Momento_cod'] = df['Momento_cod'].astype(int)

# === Entrenar modelo al inicio ===
X = df[['Presupuesto', 'Tiempo invertido', 'Tipo_cod', 'Momento_cod', 'No. de personas']]
y = df['Costo']
modelo = RandomForestRegressor(n_estimators=100, random_state=42)
modelo.fit(X, y)

# === Entrada del usuario ===
st.header('Datos de tu actividad')

presupuesto = st.number_input('Presupuesto (MXN):', min_value=0, value=100, step=10)
tiempo = st.number_input('Tiempo invertido (minutos):', min_value=1, value=15, step=5)

tipo_label = st.selectbox('Tipo de actividad:', ['Alimentos/Salud', 'Transporte', 'Entretenimiento'])
tipo_cod = 1 if tipo_label == 'Alimentos/Salud' else (6 if tipo_label == 'Transporte' else 4)

momento_label = st.selectbox('Momento del día:', ['Mañana', 'Tarde', 'Noche'])
momento_cod = 1 if momento_label == 'Mañana' else (2 if momento_label == 'Tarde' else 3)

personas = st.number_input('Número de personas:', min_value=1, value=1, step=1)

# === Predecir ===
if st.button("🔍 Predecir costo"):
    entrada = pd.DataFrame([[presupuesto, tiempo, tipo_cod, momento_cod, personas]],
                          columns=['Presupuesto', 'Tiempo invertido', 'Tipo_cod', 'Momento_cod', 'No. de personas'])

    prediccion = modelo.predict(entrada)[0]

    st.subheader("Resultado")
    st.write(f"**Costo estimado: ${prediccion:,.2f} MXN**")

    if prediccion > presupuesto:
        st.warning("¡Cuidado! El gasto estimado supera tu presupuesto.")
    else:
        st.success("¡Excelente! Estás dentro de tu presupuesto.")